name: Continuios Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: setup .net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: start sql server
        run: |
            docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=mohamed@22' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest;

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
            time: '5s'

      - name: Restore dependancies 
        run: dotnet restore
      
      - name: build the project
        run: dotnet build -c Release --no-restore

      - name : run tests
        env:
            ConnectionStrings__DefaultConnection: 'Data Source=localhost; Initial Catalog=Test2; User=sa; Password=mohamed@22' 

        run: dotnet test -c Release 

